<?php
$packages = [
    [
        'link' => '#',
        'alt' => ' National Museum of Unity Package',
        'image' => 'assets/images/Destination/image18.jpg',
        'title' => ' National Museum of Unity Package',
        'days' => '8 Day 7 Night',
        'rating' => 4.8,
        'price' => 510,
        'package_url' => 'tour-packages/france-tour-package.html',
    ],
    [
        'image' => 'assets/images/Destination/image6.jpg',
        'alt' => ' Iyi Nzu Waterfall Package',
        'title' => ' Iyi Nzu Waterfall Package',
        'days' => '5 Day 4 Night',
        'rating' => 4.8,
        'price' => 110,
        'link' => '/',
    ],
    [
        'link' => '/',
        'alt' => 'Michael Okpara Square Package',
        'image' => 'assets/images/Destination/image9.jpg',
        'title' => 'Michael Okpara Square Package',
        'days' => '4 Day 3 Night',
        'rating' => 5.0,
        'price' => 320,
        'package_url' => '/',
    ],
    [
        'link' => '#',
        'alt' => 'Akwuke Beach Package',
        'image' => 'assets/images/Destination/image8.jpg',
        'title' => 'Akwuke Beach Package',
        'days' => '8 Day 7 Night',
        'rating' => 4.8,
        'price' => 320,
        'package_url' => '',
    ],
    [
        'link' => '#',
        'alt' => 'Oji Alum Package',
        'image' => 'assets/images/Destination/image12.jpg',
        'title' => '. Oji Alum Package',
        'days' => '5 Day 4 Night ',
        'rating' => 4.8,
        'price' => 110,
        'package_url' => '',
    ],
    [
        'link' => '#',

        'alt' => 'Ngwo Pine Forest Package',
        'image' => 'assets/images/Destination/image10.jpg',
        'title' => 'Ngwo Pine Forest Package',
        'days' => '4 Day 3 Night',
        'rating' => 5.0,
        'price' => 320,
        'package_url' => '',
    ],
    [
        'link' => '#',
        'alt' => 'Milliken Hill Package',
        'image' => 'assets/images/Destination/image11.jpg',
        'title' => 'Milliken Hill Package',
        'days' => '8 Day 7 Night',
        'rating' => 4.8,
        'price' => 510,
        'package_url' => 'tour-packages/france-tour-package.html',
    ],

    [
        'link' => '#',

        'alt' => 'Unity Park Package',
        'image' => 'assets/images/Destination/image5.jpg',
        'title' => 'Unity Park Package',
        'days' => '4 Day 3 Night',
        'rating' => 5.0,
        'price' => 320,
        'package_url' => '',
    ],
];

?>
